= segtrs
:author: Sergio E. Garcia Tapia
//:toc:
:source-highlighter: rouge
:imagesdir: ./images
:figure-caption: Figure
:xrefstyle: short
:stem: latexmath
:icons: font

The name of this package is derived from my initials and the extension for
Rust source files.

This package contains my implementations of miscellaneous functions that I
coded to help me solve (usually) math-related challenges. The purpose of this
package is to encapsulate functionality that I found myself having to reuse
over and over during these challenges. Also, it serves as practice as I gain
familiarity and comfort with using Rust while solving interesting problems.
Most of these I implemented while reading The Rust Programming Language
("The Book"). Because the main purpose is to learn Rust, this document may
also contain hints for myself.

== Testing

As explained in https://doc.rust-lang.org/book/ch11-01-writing-tests.html[Section 11.1 of "The Book"],
unit tests live alongside the functions they test. They can be run with:

[source,test]
----
# Run all tests, including Doctests.
cargo test
----
